module.exports = {
    "confused": ":confusedparrot:",
    "baffled": ":confusedparrot:",
    "befuddled": ":confusedparrot:",
    "bewildered": ":confusedparrot:",
    "dazed": ":confusedparrot:",
    "disorganized": ":confusedparrot:",
    "distracted": ":confusedparrot:",
    "muddled": ":confusedparrot:",
    "perplexed": ":confusedparrot:",
    "perturbed": ":confusedparrot:",
    "puzzled": ":confusedparrot:",
    "abashed": ":confusedparrot:",
    "addled": ":confusedparrot:",
    "discombobulated": ":confusedparrot:",
    "disconcerted": ":confusedparrot:",
    "flummoxed": ":confusedparrot:",
    "flustered": ":confusedparrot:",
    "gone": ":confusedparrot:",
    "misled": ":confusedparrot:",
    "nonplussed": ":confusedparrot:",
    "stumped": ":confusedparrot:",
    "thrown": ":confusedparrot:",
    "unscrewed": ":confusedparrot:",
    "unzipped": ":confusedparrot:",
    "wtf": ":confusedparrot:",
    "?": ":confusedparrot:",
    "??": ":confusedparrot:",
    "???": ":confusedparrot:",



    "ryangosling": ":ryangoslingparrot:",

    "matrix": ":matrixparrot:",
    "cast": ":matrixparrot:",
    "forge": ":matrixparrot:",
    "form": ":matrixparrot:",
    "grid": ":matrixparrot:",
    "model": ":matrixparrot:",
    "mold": ":matrixparrot:",
    "origin": ":matrixparrot:",
    "pattern": ":matrixparrot:",
    "source": ":matrixparrot:",
    "womb": ":matrixparrot:",


    "sassy": ":sassyparrot:",
    "arrant": ":sassyparrot:",
    "audacious": ":sassyparrot:",
    "bold": ":sassyparrot:",
    "brassy": ":sassyparrot:",
    "brazen": ":sassyparrot:",
    "cheeky": ":sassyparrot:",
    "discourteous": ":sassyparrot:",
    "disrespectful": ":sassyparrot:",
    "flip": ":sassyparrot:",
    "flippant": ":sassyparrot:",
    "fresh": ":sassyparrot:",
    "insolent": ":sassyparrot:",
    "mouthy": ":sassyparrot:",
    "overbold": ":sassyparrot:",
    "rude": ":sassyparrot:",
    "saucy": ":sassyparrot:",
    "wise": ":sassyparrot:",


    "slomo": ":slomoparrot:",

    "banana": ":bananaparrot:",

    "love": ":loveparrot:",
    "affection": ":loveparrot:",
    "appreciation": ":loveparrot:",
    "devotion": ":loveparrot:",
    "emotion": ":loveparrot:",
    "fondness": ":loveparrot:",
    "friendship": ":loveparrot:",
    "infatuation": ":loveparrot:",
    "lust": ":loveparrot:",
    "passion": ":loveparrot:",
    "respect": ":loveparrot:",
    "taste": ":loveparrot:",
    "tenderness": ":loveparrot:",
    "yearning": ":loveparrot:",
    "adulation": ":loveparrot:",
    "allegiance": ":loveparrot:",
    "amity": ":loveparrot:",
    "amorousness": ":loveparrot:",
    "amour": ":loveparrot:",
    "ardor": ":loveparrot:",
    "attachment": ":loveparrot:",
    "case": ":loveparrot:",
    "cherishing": ":loveparrot:",
    "crush": ":loveparrot:",
    "delight": ":loveparrot:",
    "devotedness": ":loveparrot:",
    "enchantment": ":loveparrot:",
    "enjoyment": ":loveparrot:",
    "fervor": ":loveparrot:",
    "fidelity": ":loveparrot:",
    "flame": ":loveparrot:",
    "hankering": ":loveparrot:",
    "idolatry": ":loveparrot:",
    "inclination": ":loveparrot:",
    "involvement": ":loveparrot:",
    "like": ":loveparrot:",
    "partiality": ":loveparrot:",
    "piety": ":loveparrot:",
    "rapture": ":loveparrot:",
    "regard": ":loveparrot:",
    "relish": ":loveparrot:",
    "sentiment": ":loveparrot:",
    "weakness": ":loveparrot:",
    "worship": ":loveparrot:",
    "zeal": ":loveparrot:",
    "ardency": ":loveparrot:",
    "heart": ":loveparrot:",

    "owl": ":partyowl:",
    "party owl": ":partyowl:",
    "bandit": ":partyowl:",
    "burglar": ":partyowl:",
    "criminal": ":partyowl:",
    "crook": ":partyowl:",
    "mugger": ":partyowl:",
    "pickpocket": ":partyowl:",
    "pirate": ":partyowl:",
    "robber": ":partyowl:",
    "sniper": ":partyowl:",
    "swindler": ":partyowl:",
    "cheat": ":partyowl:",
    "clip": ":partyowl:",
    "defalcator": ":partyowl:",
    "embezzler": ":partyowl:",
    "hijacker": ":partyowl:",
    "housebreaker": ":partyowl:",
    "kleptomaniac": ":partyowl:",
    "larcener": ":partyowl:",
    "larcenist": ":partyowl:",
    "lifter": ":partyowl:",
    "moonlighter": ":partyowl:",
    "owl": ":partyowl:",
    "pilferer": ":partyowl:",
    "plunderer": ":partyowl:",
    "prowler": ":partyowl:",
    "punk": ":partyowl:",
    "scrounger": ":partyowl:",
    "shoplifter": ":partyowl:",
    "spider": ":partyowl:",
    "stealer": ":partyowl:",

    "chill": ":chillparrot:",
    "biting": ":chillparrot:",
    "chilly": ":chillparrot:",
    "freezing": ":chillparrot:",
    "frigid": ":chillparrot:",
    "frosty": ":chillparrot:",
    "icy": ":chillparrot:",
    "wintry": ":chillparrot:",
    "arctic": ":chillparrot:",
    "brisk": ":chillparrot:",
    "cool": ":chillparrot:",
    "sharp": ":chillparrot:",
    "bleak": ":chillparrot:",
    "gelid": ":chillparrot:",
    "glacial": ":chillparrot:",
    "nippy": ":chillparrot:",
    "calm": ":chillparrot:",
    "lie down": ":chillparrot:",
    "loosen up": ":chillparrot:",
    "recline": ":chillparrot:",
    "sit back": ":chillparrot:",
    "soften": ":chillparrot:",
    "unwind": ":chillparrot:",
    "laze": ":chillparrot:",
    "repose": ":chillparrot:",
    "rest": ":chillparrot:",
    "tranquilize": ":chillparrot:",
    "unbend": ":chillparrot:",
    "unlax": ":chillparrot:",


    "orioles": ":oriolesparrot:",
    "evil": ":evilparrot:",
    "bad": ":evilparrot:",
    "corrupt": ":evilparrot:",
    "destructive": ":evilparrot:",
    "hateful": ":evilparrot:",
    "heinous": ":evilparrot:",
    "hideous": ":evilparrot:",
    "malevolent": ":evilparrot:",
    "malicious": ":evilparrot:",
    "nefarious": ":evilparrot:",
    "ugly": ":evilparrot:",
    "unpleasant": ":evilparrot:",
    "vicious": ":evilparrot:",
    "vile": ":evilparrot:",
    "villainous": ":evilparrot:",
    "wicked": ":evilparrot:",
    "base": ":evilparrot:",
    "foul": ":evilparrot:",
    "low": ":evilparrot:",
    "offensive": ":evilparrot:",
    "poison": ":evilparrot:",
    "reprobate": ":evilparrot:",
    "wrong": ":evilparrot:",
    "angry": ":evilparrot:",
    "atrocious": ":evilparrot:",
    "baneful": ":evilparrot:",
    "beastly": ":evilparrot:",
    "calamitous": ":evilparrot:",
    "damnable": ":evilparrot:",
    "depraved": ":evilparrot:",
    "disastrous": ":evilparrot:",
    "execrable": ":evilparrot:",
    "flagitious": ":evilparrot:",
    "harmful": ":evilparrot:",
    "iniquitous": ":evilparrot:",
    "injurious": ":evilparrot:",
    "loathsome": ":evilparrot:",
    "maleficent": ":evilparrot:",
    "malignant": ":evilparrot:",
    "no good": ":evilparrot:",
    "obscene": ":evilparrot:",
    "pernicious": ":evilparrot:",
    "rancorous": ":evilparrot:",
    "repugnant": ":evilparrot:",
    "repulsive": ":evilparrot:",
    "revolting": ":evilparrot:",
    "spiteful": ":evilparrot:",
    "stinking": ":evilparrot:",
    "unpropitious": ":evilparrot:",
    "wrathful": ":evilparrot:",


    "portal": ":portalparrot:",
    "blue portal": ":portalblueparrot:",
    "orange portal": ":portalorangeparrot:",

    "conga": ":congaparrot::congaparrot::congaparrot:",
    "disco": ":congaparrot::congaparrot::congaparrot:",
    "rock": ":congaparrot::congaparrot::congaparrot:",
    "samba": ":congaparrot::congaparrot::congaparrot:",
    "tango": ":congaparrot::congaparrot::congaparrot:",
    "waltz": ":congaparrot::congaparrot::congaparrot:",
    "Charleston": ":congaparrot::congaparrot::congaparrot:",
    "bob": ":congaparrot::congaparrot::congaparrot:",
    "boogie": ":congaparrot::congaparrot::congaparrot:",
    "caper": ":congaparrot::congaparrot::congaparrot:",
    "careen": ":congaparrot::congaparrot::congaparrot:",
    "cavort": ":congaparrot::congaparrot::congaparrot:",
    "conga": ":congaparrot::congaparrot::congaparrot:",
    "flit": ":congaparrot::congaparrot::congaparrot:",
    "foxtrot": ":congaparrot::congaparrot::congaparrot:",
    "frolic": ":congaparrot::congaparrot::congaparrot:",
    "gambol": ":congaparrot::congaparrot::congaparrot:",
    "hop": ":congaparrot::congaparrot::congaparrot:",
    "hustle": ":congaparrot::congaparrot::congaparrot:",
    "jig": ":congaparrot::congaparrot::congaparrot:",
    "jitter": ":congaparrot::congaparrot::congaparrot:",
    "jitterbug": ":congaparrot::congaparrot::congaparrot:",
    "jive": ":congaparrot::congaparrot::congaparrot:",
    "jump": ":congaparrot::congaparrot::congaparrot:",
    "leap": ":congaparrot::congaparrot::congaparrot:",
    "one-step": ":congaparrot::congaparrot::congaparrot:",
    "prance": ":congaparrot::congaparrot::congaparrot:",
    "promenade": ":congaparrot::congaparrot::congaparrot:",
    "rhumba": ":congaparrot::congaparrot::congaparrot:",
    "shimmy": ":congaparrot::congaparrot::congaparrot:",
    "skip": ":congaparrot::congaparrot::congaparrot:",
    "spin": ":congaparrot::congaparrot::congaparrot:",
    "step": ":congaparrot::congaparrot::congaparrot:",
    "strut": ":congaparrot::congaparrot::congaparrot:",
    "sway": ":congaparrot::congaparrot::congaparrot:",
    "swing": ":congaparrot::congaparrot::congaparrot:",
    "tap": ":congaparrot::congaparrot::congaparrot:",
    "tread": ":congaparrot::congaparrot::congaparrot:",
    "trip": ":congaparrot::congaparrot::congaparrot:",
    "twist": ":congaparrot::congaparrot::congaparrot:",
    "two-step": ":congaparrot::congaparrot::congaparrot:",
    "whirl": ":congaparrot::congaparrot::congaparrot:",
    "boogie down": ":congaparrot::congaparrot::congaparrot:",
    "bunny hop": ":congaparrot::congaparrot::congaparrot:",
    "cut a rug": ":congaparrot::congaparrot::congaparrot:",
    "foot it": ":congaparrot::congaparrot::congaparrot:",
    "get down": ":congaparrot::congaparrot::congaparrot:",
    "hoof it": ":congaparrot::congaparrot::congaparrot:",
    "rock n' roll": ":congaparrot::congaparrot::congaparrot:",


    "sovjet": ":sovjetparrot:",

    "poop": ":parrotpoop:",
    "crap": ":poopparrot:",
    "BM": ":poopparrot:",
    "defecation": ":poopparrot:",
    "discharge": ":poopparrot:",
    "dung": ":poopparrot:",
    "excrement": ":poopparrot:",
    "excretion": ":poopparrot:",
    "fecal matter": ":poopparrot:",
    "feces": ":poopparrot:",
    "feculence": ":poopparrot:",
    "deuce": ":poopparrot:",
    "manure": ":poopparrot:",
    "number two": ":poopparrot:",
    "shit": ":poopparrot:",
    "stool": ":poopparrot:",
    "waste": ":poopparrot:",

    "hankey": ":parrotpoop:",

    "halal": ":halalparrot:",

    "rotating": ":rotatingparrot:",
    "rotate": ":rotatingparrot:",
    "pivot": ":rotatingparrot:",
    "revolve": ":rotatingparrot:",
    "spin": ":rotatingparrot:",
    "swivel": ":rotatingparrot:",
    "twirl": ":rotatingparrot:",
    "twist": ":rotatingparrot:",
    "whirl": ":rotatingparrot:",
    "circle": ":rotatingparrot:",
    "circumvolve": ":rotatingparrot:",
    "gyrate": ":rotatingparrot:",
    "move": ":rotatingparrot:",
    "pirouette": ":rotatingparrot:",
    "reel": ":rotatingparrot:",
    "roll": ":rotatingparrot:",
    "troll": ":rotatingparrot:",
    "trundle": ":rotatingparrot:",
    "turn": ":rotatingparrot:",
    "waltz": ":rotatingparrot:",
    "wheel": ":rotatingparrot:",
    "whirligig": ":rotatingparrot:",
    "whirr": ":rotatingparrot:",
    "circumduct": ":rotatingparrot:",
    "gyre": ":rotatingparrot:",


    "cat": ":catparrot:",
    "bobcat": ":catparrot:",
    "cheetah": ":catparrot:",
    "cougar": ":catparrot:",
    "jaguar": ":catparrot:",
    "kitten": ":catparrot:",
    "kitty": ":catparrot:",
    "leopard": ":catparrot:",
    "lion": ":catparrot:",
    "lynx": ":catparrot:",
    "mouser": ":catparrot:",
    "ocelot": ":catparrot:",
    "panther": ":catparrot:",
    "puma": ":catparrot:",
    "puss": ":catparrot:",
    "pussy": ":catparrot:",
    "tabby": ":catparrot:",
    "tiger": ":catparrot:",
    "tom": ":catparrot:",
    "tomcat": ":catparrot:",
    "grimalkin": ":catparrot:",
    "malkin": ":catparrot:",


    "dark beer": ":darkbeerparrot:",

    "slow": ":slowparrot:",
    "easy": ":slowparrot:",
    "gradual": ":slowparrot:",
    "heavy": ":slowparrot:",
    "lackadaisical": ":slowparrot:",
    "leisurely": ":slowparrot:",
    "lethargic": ":slowparrot:",
    "moderate": ":slowparrot:",
    "passive": ":slowparrot:",
    "quiet": ":slowparrot:",
    "reluctant": ":slowparrot:",
    "sluggish": ":slowparrot:",
    "stagnant": ":slowparrot:",
    "crawling": ":slowparrot:",
    "creeping": ":slowparrot:",
    "dawdling": ":slowparrot:",
    "delaying": ":slowparrot:",
    "deliberate": ":slowparrot:",
    "disinclined": ":slowparrot:",
    "idle": ":slowparrot:",
    "lagging": ":slowparrot:",
    "loitering": ":slowparrot:",
    "measured": ":slowparrot:",
    "plodding": ":slowparrot:",
    "postponing": ":slowparrot:",
    "procrastinating": ":slowparrot:",
    "slack": ":slowparrot:",
    "apathetic": ":slowparrot:",
    "dilatory": ":slowparrot:",
    "dreamy": ":slowparrot:",
    "drowsy": ":slowparrot:",
    "imperceptible": ":slowparrot:",
    "inactive": ":slowparrot:",
    "indolent": ":slowparrot:",
    "inert": ":slowparrot:",
    "laggard": ":slowparrot:",
    "leaden": ":slowparrot:",
    "listless": ":slowparrot:",
    "negligent": ":slowparrot:",
    "phlegmatic": ":slowparrot:",
    "ponderous": ":slowparrot:",
    "remiss": ":slowparrot:",
    "sleepy": ":slowparrot:",
    "slothful": ":slowparrot:",
    "slow-moving": ":slowparrot:",
    "snaillike": ":slowparrot:",
    "supine": ":slowparrot:",
    "tardy": ":slowparrot:",
    "torpid": ":slowparrot:",
    "tortoiselike": ":slowparrot:",


    "crypto": ":cryptoparrot:",
    "identification": ":cryptoparrot:",
    "countersign": ":cryptoparrot:",
    "key": ":cryptoparrot:",
    "parole": ":cryptoparrot:",
    "phrase": ":cryptoparrot:",
    "signal": ":cryptoparrot:",
    "ticket": ":cryptoparrot:",
    "watchword": ":cryptoparrot:",
    "word": ":cryptoparrot:",
    "key word": ":cryptoparrot:",
    "open sesame": ":cryptoparrot:",


    "fiesta": ":fiestaparrot:",
    "feast": ":fiestaparrot:",
    "carnival": ":fiestaparrot:",
    "festival": ":fiestaparrot:",
    "holiday": ":fiestaparrot:",
    "vacation": ":fiestaparrot:",
    "holy day": ":fiestaparrot:",
    "saint's day": ":fiestaparrot:",


    "fast": ":fastparrot:",
    "agile": ":fastparrot:",
    "brisk": ":fastparrot:",
    "hot": ":fastparrot:",
    "nimble": ":fastparrot:",
    "quick": ":fastparrot:",
    "rapid": ":fastparrot:",
    "swift": ":fastparrot:",
    "accelerated": ":fastparrot:",
    "active": ":fastparrot:",
    "dashing": ":fastparrot:",
    "electric": ":fastparrot:",
    "flashing": ":fastparrot:",
    "fleet": ":fastparrot:",
    "fleeting": ":fastparrot:",
    "flying": ":fastparrot:",
    "hurried": ":fastparrot:",
    "racing": ":fastparrot:",
    "ready": ":fastparrot:",
    "snap": ":fastparrot:",
    "winged": ":fastparrot:",
    "PDQ": ":fastparrot:",
    "blue streak": ":fastparrot:",
    "breakneck": ":fastparrot:",
    "chop-chop": ":fastparrot:",
    "double-time": ":fastparrot:",
    "expeditious": ":fastparrot:",
    "expeditive": ":fastparrot:",
    "hairtrigger": ":fastparrot:",
    "hasty": ":fastparrot:",
    "hypersonic": ":fastparrot:",
    "in a jiffy": ":fastparrot:",
    "in nothing flat": ":fastparrot:",
    "lickety split": ":fastparrot:",
    "like a bat out of hell": ":fastparrot:",
    "like all get out": ":fastparrot:",
    "like crazy": ":fastparrot:",
    "like mad": ":fastparrot:",
    "on the double": ":fastparrot:",
    "posthaste": ":fastparrot:",
    "presto": ":fastparrot:",
    "pronto": ":fastparrot:",
    "screamin'": ":fastparrot:",
    "snappy": ":fastparrot:",
    "speedball": ":fastparrot:",
    "supersonic": ":fastparrot:",
    "velocious": ":fastparrot:",


    "science": ":scienceparrot:",
    "art": ":scienceparrot:",
    "discipline": ":scienceparrot:",
    "education": ":scienceparrot:",
    "information": ":scienceparrot:",
    "learning": ":scienceparrot:",
    "skill": ":scienceparrot:",
    "system": ":scienceparrot:",
    "technique": ":scienceparrot:",
    "branch": ":scienceparrot:",
    "erudition": ":scienceparrot:",
    "lore": ":scienceparrot:",
    "scholarship": ":scienceparrot:",
    "wisdom": ":scienceparrot:",
    "body of knowledge": ":scienceparrot:",


    "thumbs-up": ":thumbsupparrot:",
    "approval": ":thumbsupparrot:",
    "go-ahead": ":thumbsupparrot:",
    "green light": ":thumbsupparrot:",
    "rubber stamp": ":thumbsupparrot:",
    "satisfaction": ":thumbsupparrot:",


    "stable": ":stableparrot:",
    "balanced": ":stableparrot:",
    "calm": ":stableparrot:",
    "durable": ":stableparrot:",
    "fast": ":stableparrot:",
    "lasting": ":stableparrot:",
    "permanent": ":stableparrot:",
    "reliable": ":stableparrot:",
    "safe": ":stableparrot:",
    "secure": ":stableparrot:",
    "solid": ":stableparrot:",
    "steady": ":stableparrot:",
    "strong": ":stableparrot:",
    "substantial": ":stableparrot:",
    "abiding": ":stableparrot:",
    "anchored": ":stableparrot:",
    "enduring": ":stableparrot:",
    "established": ":stableparrot:",
    "even": ":stableparrot:",
    "firm": ":stableparrot:",
    "invariable": ":stableparrot:",
    "nailed": ":stableparrot:",
    "poised": ":stableparrot:",
    "set": ":stableparrot:",
    "sound": ":stableparrot:",
    "stabile": ":stableparrot:",
    "stalwart": ":stableparrot:",
    "staunch": ":stableparrot:",
    "stout": ":stableparrot:",
    "tough": ":stableparrot:",
    "uniform": ":stableparrot:",
    "brick-wall": ":stableparrot:",
    "deep-rooted": ":stableparrot:",
    "equable": ":stableparrot:",
    "immutable": ":stableparrot:",
    "perdurable": ":stableparrot:",
    "resolute": ":stableparrot:",
    "set in stone": ":stableparrot:",
    "solid as a rock": ":stableparrot:",
    "stationary": ":stableparrot:",
    "staying put": ":stableparrot:",
    "steadfast": ":stableparrot:",
    "sturdy": ":stableparrot:",
    "sure": ":stableparrot:",
    "together": ":stableparrot:",
    "unalterable": ":stableparrot:",
    "unchangeable": ":stableparrot:",
    "unfluctuating": ":stableparrot:",
    "unvarying": ":stableparrot:",
    "unwavering": ":stableparrot:",
    "well-built": ":stableparrot:",
    "well-founded": ":stableparrot:",


    "fieri": ":fieriparrot:",

    "explode": ":explodyparrot:",
    "boom": ":explodyparrot:",
    "blast": ":explodyparrot:",
    "break out": ":explodyparrot:",
    "burst": ":explodyparrot:",
    "collapse": ":explodyparrot:",
    "detonate": ":explodyparrot:",
    "erupt": ":explodyparrot:",
    "flare up": ":explodyparrot:",
    "mushroom": ":explodyparrot:",
    "rupture": ":explodyparrot:",
    "set off": ":explodyparrot:",
    "shatter": ":explodyparrot:",
    "backfire": ":explodyparrot:",
    "blaze": ":explodyparrot:",
    "convulse": ":explodyparrot:",
    "discharge": ":explodyparrot:",
    "fracture": ":explodyparrot:",
    "jet": ":explodyparrot:",
    "shiver": ":explodyparrot:",
    "split": ":explodyparrot:",
    "thunder": ":explodyparrot:",
    "blow to kingdom come": ":explodyparrot:",
    "flame up": ":explodyparrot:",
    "kablooey": ":explodyparrot:",
    "let go": ":explodyparrot:",


    "ultrafast": ":ultrafastparrot:",

    "doge": ":dogeparrot:",

    "margarita": ":margaritaparrot:",

    "beret": ":beretparrot:",
    "beret": ":beretparrot:",
    "DINK": ":beretparrot:",
    "beanie": ":beretparrot:",
    "bonnet": ":beretparrot:",
    "fez": ":beretparrot:",
    "pillbox": ":beretparrot:",
    "skullcap": ":beretparrot:",
    "tam": ":beretparrot:",


    "angry": ":angryparrot:",
    "mad": ":angryparrot:",
    "annoyed": ":angryparrot:",
    "bitter": ":angryparrot:",
    "enraged": ":angryparrot:",
    "exasperated": ":angryparrot:",
    "furious": ":angryparrot:",
    "heated": ":angryparrot:",
    "impassioned": ":angryparrot:",
    "indignant": ":angryparrot:",
    "irate": ":angryparrot:",
    "irritable": ":angryparrot:",
    "irritated": ":angryparrot:",
    "offended": ":angryparrot:",
    "outraged": ":angryparrot:",
    "resentful": ":angryparrot:",
    "sullen": ":angryparrot:",
    "uptight": ":angryparrot:",
    "affronted": ":angryparrot:",
    "antagonized": ":angryparrot:",
    "chafed": ":angryparrot:",
    "choleric": ":angryparrot:",
    "convulsed": ":angryparrot:",
    "cross": ":angryparrot:",
    "displeased": ":angryparrot:",
    "exacerbated": ":angryparrot:",
    "ferocious": ":angryparrot:",
    "fierce": ":angryparrot:",
    "fiery": ":angryparrot:",
    "fuming": ":angryparrot:",
    "galled": ":angryparrot:",
    "hateful": ":angryparrot:",
    "hot": ":angryparrot:",
    "huffy": ":angryparrot:",
    "ill-tempered": ":angryparrot:",
    "incensed": ":angryparrot:",
    "inflamed": ":angryparrot:",
    "infuriated": ":angryparrot:",
    "irascible": ":angryparrot:",
    "ireful": ":angryparrot:",
    "maddened": ":angryparrot:",
    "nettled": ":angryparrot:",
    "piqued": ":angryparrot:",
    "provoked": ":angryparrot:",
    "raging": ":angryparrot:",
    "riled": ":angryparrot:",
    "sore": ":angryparrot:",
    "splenetic": ":angryparrot:",
    "storming": ":angryparrot:",
    "sulky": ":angryparrot:",
    "tumultous": ":angryparrot:",
    "turbulent": ":angryparrot:",
    "vexed": ":angryparrot:",
    "wrathful": ":angryparrot:",


    "hamburger": ":hamburgerparrot:",
    "beefburger": ":hamburgerparrot:",
    "burger": ":hamburgerparrot:",
    "cheeseburger": ":hamburgerparrot:",
    "Salisbury steak": ":hamburgerparrot:",
    "chopped beefsteak": ":hamburgerparrot:",
    "ground chuck": ":hamburgerparrot:",
    "ground round": ":hamburgerparrot:",
    "ground sirloin": ":hamburgerparrot:",


    "shuffle": ":shuffleparrot:",
    "drag": "shuffleparrot:",
    "limp": "shuffleparrot:",
    "straggle": "shuffleparrot:",
    "stumble": "shuffleparrot:",
    "muddle": "shuffleparrot:",
    "pad": "shuffleparrot:",
    "scrape": "shuffleparrot:",
    "scuff": "shuffleparrot:",
    "scuffle": "shuffleparrot:",
    "shamble": "shuffleparrot:",
    "trail": "shuffleparrot:",


    "ice-cream": ":ice-cream-parrot:",
    "frozen yogurt": "ice-cream-parrot:",
    "sherbet": "ice-cream-parrot:",
    "sorbet": "ice-cream-parrot:",
    "gelato": "ice-cream-parrot:",
    "ice": "ice-cream-parrot:",
    "ice milk": "ice-cream-parrot:",


    "brazilian fan": ":brazilianfanparrot:",

    "coffee": ":coffeeparrot:",
    "caffeine": "coffeeparrot:",
    "cappuccino": "coffeeparrot:",
    "espresso": "coffeeparrot:",
    "brew": "coffeeparrot:",
    "decaf": "coffeeparrot:",
    "decoction": "coffeeparrot:",
    "demitasse": "coffeeparrot:",
    "ink": "coffeeparrot:",
    "java": "coffeeparrot:",
    "mocha": "coffeeparrot:",
    "mud": "coffeeparrot:",
    "perk": "coffeeparrot:",
    "battery acid": "coffeeparrot:",
    "café": "coffeeparrot:",
    "café au lait": "coffeeparrot:",
    "café noir": "coffeeparrot:",
    "forty weight": "coffeeparrot:",
    "hot stuff": "coffeeparrot:",
    "jamocha": "coffeeparrot:",


    "conga doge": ":congadoge:",

    "christmas": ":christmasparrot:",
    "Christmastide": "christmasparrot:",
    "Noel": "christmasparrot:",
    "Xmas": "christmasparrot:",
    "Yule": "christmasparrot:",
    "Yuletide": "christmasparrot:",
    "Christmas Day": "christmasparrot:",
    "Christmas Eve": "christmasparrot:",
    "Christmas night": "christmasparrot:",
    "the Nativity": "christmasparrot:",


    "pride": ":prideparrot:",
    "delight": "prideparrot:",
    "dignity": "prideparrot:",
    "ego": "prideparrot:",
    "happiness": "prideparrot:",
    "honor": "prideparrot:",
    "joy": "prideparrot:",
    "pleasure": "prideparrot:",
    "satisfaction": "prideparrot:",
    "self-confidence": "prideparrot:",
    "self-respect": "prideparrot:",
    "egoism": "prideparrot:",
    "egotism": "prideparrot:",
    "face": "prideparrot:",
    "gratification": "prideparrot:",
    "pridefulness": "prideparrot:",
    "repletion": "prideparrot:",
    "self-love": "prideparrot:",
    "self-regard": "prideparrot:",
    "self-satisfaction": "prideparrot:",
    "self-sufficiency": "prideparrot:",
    "self-worth": "prideparrot:",
    "sufficiency": "prideparrot:",
    "amour-propre": "prideparrot:",
    "ego trip": "prideparrot:",
    "self-admiration": "prideparrot:",
    "self-glorification": "prideparrot:",
    "self-trust": "prideparrot:",


    "blonde": ":blondesassyparrot:",

    "fix": ":fixparrot:",
    "mend": ":fixparrot:",

    "triplets": ":tripletsparrot:",

    "harry potter": ":harrypotterparrot:",

    "lucky": ":luckyparrot:",

    "right": ":rightparrot:",

    "ship it": ":shipitparrot:",
    "release": ":shipitparrot:",

    "angel": ":angelparrot:",

    "shuffle further": ":shufflefurtherparrot:",

    "caps": ":capsparrot:",

    "aussie": ":aussieparrot:",

    "deal with it": ":dealwithitparrot:",

    "stalker": ":stalkerparrot:",

    "ski": ":skiparrot:",

    "nyan": ":nyanparrot:",

    "gentleman": ":gentlemanparrot:",

    "papal": ":papalparrot:",

    "cops": ":parrotcop:",
    "police": ":parrotcop:",

    "witness protection": ":witnessprotectionparrot:",
    "secret": ":witnessprotectionparrot:",
    "hide": ":witnessprotectionparrot:",

    "dreidel": ":dreidelparrot:",

    "aussie reverse conga": ":aussiereversecongaparrot:",

    "dad": ":parrotdad:",
    "papa": ":parrotdad:",
    "father": ":parrotdad:",

    "sad": ":sadparrot:",
    "upset": ":sadparrot:",
    "cry": ":sadparrot:",

    "old timer": ":oldtimeyparrot:",
    "old": ":oldtimeyparrot:",

    "wave": ":parrotwave1::parrotwave2::parrotwave3::parrotwave4::parrotwave5::parrotwave6::parrotwave7:",
    "mexican wave": ":parrotwave1::parrotwave2::parrotwave3::parrotwave4::parrotwave5::parrotwave6::parrotwave7:",

    "pizza": ":pizzaparrot:",

    "mustache": ":parrotmustache:",

    "aussie conga": ":aussiecongaparrot:",

    "moonwalking": ":moonwalkingparrot:",

    "fidget": ":fidgetparrot:",

    "taco": ":tacoparrot:",

    "goth": ":gothparrot:",

    "invisible": ":invisibleparrot:",
    "ghost": ":invisibleparrot:",

    "bored": ":boredparrot:",
    "fed-up": ":boredparrot:",

    "blues clues": ":bluescluesparrot:",

    "upvote": ":upvotepartyparrot:",

    "reverse conga": ":reversecongaparrot:",

    "twins": ":twinsparrot:",
    "double": ":twinsparrot:",

    "opensource": ":opensourceparrot:",
    "programming": ":opensourceparrot:",
    "coding": ":opensourceparrot:",

    "brazilianplayer": ":brazilianplayerparrot:",

    "ceiling": ":ceilingparrot:",
    "roof": ":ceilingparrot:",

    "conga party": ":congapartyparrot:",

    "middle": ":middleparrot:",

    "party": ":partyparrot:",

    "sleep": ":parrotsleep:",
    "tired": ":parrotsleep:",
    "sleepy": ":parrotsleep:",
    "bed": ":parrotsleep:",

    "beer": ":parrotbeer:",
    "wine": ":parrotbeer:",
    "alchohol": ":parrotbeer:",
    "pub": ":parrotbeer:",

    "shuffle party": ":shufflepartyparrot:",

    "parrot": ":parrot:"
}
