module.exports = {
    "confused": ":confusedparrot:",
    "baffled": ":confusedparrot:",
    "befuddled": ":confusedparrot:",
    "bewildered": ":confusedparrot:",
    "dazed": ":confusedparrot:",
    "disorganized": ":confusedparrot:",
    "distracted": ":confusedparrot:",
    "muddled": ":confusedparrot:",
    "perplexed": ":confusedparrot:",
    "perturbed": ":confusedparrot:",
    "puzzled": ":confusedparrot:",
    "abashed": ":confusedparrot:",
    "addled": ":confusedparrot:",
    "discombobulated": ":confusedparrot:",
    "disconcerted": ":confusedparrot:",
    "flummoxed": ":confusedparrot:",
    "flustered": ":confusedparrot:",
    "misled": ":confusedparrot:",
    "nonplussed": ":confusedparrot:",
    "stumped": ":confusedparrot:",
    "thrown": ":confusedparrot:",
    "unscrewed": ":confusedparrot:",
    "unzipped": ":confusedparrot:",
    "wtf": ":confusedparrot:",
    "?": ":confusedparrot:",
    "??": ":confusedparrot:",
    "???": ":confusedparrot:",



    "ryangosling": ":ryangoslingparrot:",

    "matrix": ":matrixparrot:",
    "cast": ":matrixparrot:",
    "forge": ":matrixparrot:",
    "form": ":matrixparrot:",
    "mold": ":matrixparrot:",
    "origin": ":matrixparrot:",
    "pattern": ":matrixparrot:",
    "source": ":matrixparrot:",


    "sassy": ":sassyparrot:",
    "arrant": ":sassyparrot:",
    "audacious": ":sassyparrot:",
    "bold": ":sassyparrot:",
    "brassy": ":sassyparrot:",
    "brazen": ":sassyparrot:",
    "cheeky": ":sassyparrot:",
    "discourteous": ":sassyparrot:",
    "disrespectful": ":sassyparrot:",
    "flippant": ":sassyparrot:",
    "insolent": ":sassyparrot:",
    "mouthy": ":sassyparrot:",
    "overbold": ":sassyparrot:",
    "rude": ":sassyparrot:",
    "saucy": ":sassyparrot:",
    "wise": ":sassyparrot:",


    "slomo": ":slomoparrot:",

    "banana": ":bananaparrot:",

    "love": ":loveparrot:",
    "affection": ":loveparrot:",
    "appreciation": ":loveparrot:",
    "devotion": ":loveparrot:",
    "emotion": ":loveparrot:",
    "fondness": ":loveparrot:",
    "friendship": ":loveparrot:",
    "infatuation": ":loveparrot:",
    "lust": ":loveparrot:",
    "passion": ":loveparrot:",
    "respect": ":loveparrot:",
    "tenderness": ":loveparrot:",
    "yearning": ":loveparrot:",
    "adulation": ":loveparrot:",
    "allegiance": ":loveparrot:",
    "amity": ":loveparrot:",
    "amorousness": ":loveparrot:",
    "amour": ":loveparrot:",
    "ardor": ":loveparrot:",
    "attachment": ":loveparrot:",
    "cherishing": ":loveparrot:",
    "crush": ":loveparrot:",
    "delight": ":loveparrot:",
    "devotedness": ":loveparrot:",
    "enchantment": ":loveparrot:",
    "enjoyment": ":loveparrot:",
    "fervor": ":loveparrot:",
    "fidelity": ":loveparrot:",
    "hankering": ":loveparrot:",
    "idolatry": ":loveparrot:",
    "inclination": ":loveparrot:",
    "involvement": ":loveparrot:",
    "partiality": ":loveparrot:",
    "piety": ":loveparrot:",
    "rapture": ":loveparrot:",
    "regard": ":loveparrot:",
    "relish": ":loveparrot:",
    "sentiment": ":loveparrot:",
    "weakness": ":loveparrot:",
    "worship": ":loveparrot:",
    "zeal": ":loveparrot:",
    "ardency": ":loveparrot:",
    "heart": ":loveparrot:",

    "owl": ":partyowl:",
    "party owl": ":partyowl:",
    "bandit": ":partyowl:",
    "burglar": ":partyowl:",
    "criminal": ":partyowl:",
    "crook": ":partyowl:",
    "mugger": ":partyowl:",
    "pickpocket": ":partyowl:",
    "pirate": ":partyowl:",
    "robber": ":partyowl:",
    "sniper": ":partyowl:",
    "swindler": ":partyowl:",
    "cheat": ":partyowl:",
    "clip": ":partyowl:",
    "defalcator": ":partyowl:",
    "embezzler": ":partyowl:",
    "hijacker": ":partyowl:",
    "housebreaker": ":partyowl:",
    "kleptomaniac": ":partyowl:",
    "larcener": ":partyowl:",
    "larcenist": ":partyowl:",
    "lifter": ":partyowl:",
    "moonlighter": ":partyowl:",
    "pilferer": ":partyowl:",
    "plunderer": ":partyowl:",
    "prowler": ":partyowl:",
    "punk": ":partyowl:",
    "scrounger": ":partyowl:",
    "shoplifter": ":partyowl:",
    "spider": ":partyowl:",
    "stealer": ":partyowl:",

    "chill": ":chillparrot:",
    "biting": ":chillparrot:",
    "chilly": ":chillparrot:",
    "freezing": ":chillparrot:",
    "frigid": ":chillparrot:",
    "frosty": ":chillparrot:",
    "icy": ":chillparrot:",
    "wintry": ":chillparrot:",
    "arctic": ":chillparrot:",
    "cool": ":chillparrot:",
    "sharp": ":chillparrot:",
    "bleak": ":chillparrot:",
    "gelid": ":chillparrot:",
    "glacial": ":chillparrot:",
    "nippy": ":chillparrot:",
    "lie down": ":chillparrot:",
    "loosen up": ":chillparrot:",
    "recline": ":chillparrot:",
    "sit back": ":chillparrot:",
    "soften": ":chillparrot:",
    "unwind": ":chillparrot:",
    "laze": ":chillparrot:",
    "tranquilize": ":chillparrot:",
    "unbend": ":chillparrot:",
    "unlax": ":chillparrot:",


    "orioles": ":oriolesparrot:",
    "evil": ":evilparrot:",
    "bad": ":evilparrot:",
    "corrupt": ":evilparrot:",
    "destructive": ":evilparrot:",
    "hateful": ":evilparrot:",
    "heinous": ":evilparrot:",
    "hideous": ":evilparrot:",
    "malevolent": ":evilparrot:",
    "malicious": ":evilparrot:",
    "nefarious": ":evilparrot:",
    "ugly": ":evilparrot:",
    "unpleasant": ":evilparrot:",
    "vicious": ":evilparrot:",
    "vile": ":evilparrot:",
    "villainous": ":evilparrot:",
    "wicked": ":evilparrot:",
    "base": ":evilparrot:",
    "foul": ":evilparrot:",
    "offensive": ":evilparrot:",
    "poison": ":evilparrot:",
    "reprobate": ":evilparrot:",
    "wrong": ":evilparrot:",
    "atrocious": ":evilparrot:",
    "baneful": ":evilparrot:",
    "beastly": ":evilparrot:",
    "calamitous": ":evilparrot:",
    "damnable": ":evilparrot:",
    "depraved": ":evilparrot:",
    "disastrous": ":evilparrot:",
    "execrable": ":evilparrot:",
    "flagitious": ":evilparrot:",
    "harmful": ":evilparrot:",
    "iniquitous": ":evilparrot:",
    "injurious": ":evilparrot:",
    "loathsome": ":evilparrot:",
    "maleficent": ":evilparrot:",
    "malignant": ":evilparrot:",
    "no good": ":evilparrot:",
    "obscene": ":evilparrot:",
    "pernicious": ":evilparrot:",
    "rancorous": ":evilparrot:",
    "repugnant": ":evilparrot:",
    "repulsive": ":evilparrot:",
    "revolting": ":evilparrot:",
    "spiteful": ":evilparrot:",
    "stinking": ":evilparrot:",
    "unpropitious": ":evilparrot:",
    "wrathful": ":evilparrot:",


    "portal": ":portalparrot:",
    "blue portal": ":portalblueparrot:",
    "orange portal": ":portalorangeparrot:",

    "conga": ":congaparrot::congaparrot::congaparrot:",
    "disco": ":congaparrot::congaparrot::congaparrot:",
    "rock": ":congaparrot::congaparrot::congaparrot:",
    "samba": ":congaparrot::congaparrot::congaparrot:",
    "tango": ":congaparrot::congaparrot::congaparrot:",
    "waltz": ":congaparrot::congaparrot::congaparrot:",
    "Charleston": ":congaparrot::congaparrot::congaparrot:",
    "bob": ":congaparrot::congaparrot::congaparrot:",
    "boogie": ":congaparrot::congaparrot::congaparrot:",
    "caper": ":congaparrot::congaparrot::congaparrot:",
    "careen": ":congaparrot::congaparrot::congaparrot:",
    "cavort": ":congaparrot::congaparrot::congaparrot:",
    "flit": ":congaparrot::congaparrot::congaparrot:",
    "foxtrot": ":congaparrot::congaparrot::congaparrot:",
    "frolic": ":congaparrot::congaparrot::congaparrot:",
    "gambol": ":congaparrot::congaparrot::congaparrot:",
    "hop": ":congaparrot::congaparrot::congaparrot:",
    "hustle": ":congaparrot::congaparrot::congaparrot:",
    "jig": ":congaparrot::congaparrot::congaparrot:",
    "jitterbug": ":congaparrot::congaparrot::congaparrot:",
    "jive": ":congaparrot::congaparrot::congaparrot:",
    "jump": ":congaparrot::congaparrot::congaparrot:",
    "leap": ":congaparrot::congaparrot::congaparrot:",
    "one-step": ":congaparrot::congaparrot::congaparrot:",
    "prance": ":congaparrot::congaparrot::congaparrot:",
    "promenade": ":congaparrot::congaparrot::congaparrot:",
    "rhumba": ":congaparrot::congaparrot::congaparrot:",
    "shimmy": ":congaparrot::congaparrot::congaparrot:",
    "skip": ":congaparrot::congaparrot::congaparrot:",
    "step": ":congaparrot::congaparrot::congaparrot:",
    "strut": ":congaparrot::congaparrot::congaparrot:",
    "sway": ":congaparrot::congaparrot::congaparrot:",
    "swing": ":congaparrot::congaparrot::congaparrot:",
    "tap": ":congaparrot::congaparrot::congaparrot:",
    "tread": ":congaparrot::congaparrot::congaparrot:",
    "trip": ":congaparrot::congaparrot::congaparrot:",
    "two-step": ":congaparrot::congaparrot::congaparrot:",
    "boogie down": ":congaparrot::congaparrot::congaparrot:",
    "bunny hop": ":congaparrot::congaparrot::congaparrot:",
    "cut a rug": ":congaparrot::congaparrot::congaparrot:",
    "foot it": ":congaparrot::congaparrot::congaparrot:",
    "get down": ":congaparrot::congaparrot::congaparrot:",
    "hoof it": ":congaparrot::congaparrot::congaparrot:",
    "rock n' roll": ":congaparrot::congaparrot::congaparrot:",


    "sovjet": ":sovjetparrot:",

    "poop": ":parrotpoop:",
    "crap": ":poopparrot:",
    "BM": ":poopparrot:",
    "defecation": ":poopparrot:",
    "dung": ":poopparrot:",
    "excrement": ":poopparrot:",
    "excretion": ":poopparrot:",
    "fecal matter": ":poopparrot:",
    "feces": ":poopparrot:",
    "feculence": ":poopparrot:",
    "deuce": ":poopparrot:",
    "manure": ":poopparrot:",
    "number two": ":poopparrot:",
    "shit": ":poopparrot:",
    "stool": ":poopparrot:",
    "waste": ":poopparrot:",

    "hankey": ":parrotpoop:",

    "halal": ":halalparrot:",

    "rotating": ":rotatingparrot:",
    "rotate": ":rotatingparrot:",
    "pivot": ":rotatingparrot:",
    "revolve": ":rotatingparrot:",
    "spin": ":rotatingparrot:",
    "swivel": ":rotatingparrot:",
    "twirl": ":rotatingparrot:",
    "twist": ":rotatingparrot:",
    "whirl": ":rotatingparrot:",
    "circle": ":rotatingparrot:",
    "circumvolve": ":rotatingparrot:",
    "gyrate": ":rotatingparrot:",
    "pirouette": ":rotatingparrot:",
    "reel": ":rotatingparrot:",
    "roll": ":rotatingparrot:",
    "troll": ":rotatingparrot:",
    "trundle": ":rotatingparrot:",
    "turn": ":rotatingparrot:",
    "wheel": ":rotatingparrot:",
    "whirligig": ":rotatingparrot:",
    "whirr": ":rotatingparrot:",
    "circumduct": ":rotatingparrot:",
    "gyre": ":rotatingparrot:",


    "cat": ":catparrot:",
    "bobcat": ":catparrot:",
    "cheetah": ":catparrot:",
    "cougar": ":catparrot:",
    "jaguar": ":catparrot:",
    "kitten": ":catparrot:",
    "kitty": ":catparrot:",
    "leopard": ":catparrot:",
    "lion": ":catparrot:",
    "lynx": ":catparrot:",
    "mouser": ":catparrot:",
    "ocelot": ":catparrot:",
    "panther": ":catparrot:",
    "puma": ":catparrot:",
    "puss": ":catparrot:",
    "pussy": ":catparrot:",
    "tabby": ":catparrot:",
    "tiger": ":catparrot:",
    "tom": ":catparrot:",
    "tomcat": ":catparrot:",
    "grimalkin": ":catparrot:",
    "malkin": ":catparrot:",


    "dark beer": ":darkbeerparrot:",

    "slow": ":slowparrot:",
    "easy": ":slowparrot:",
    "gradual": ":slowparrot:",
    "heavy": ":slowparrot:",
    "lackadaisical": ":slowparrot:",
    "leisurely": ":slowparrot:",
    "lethargic": ":slowparrot:",
    "moderate": ":slowparrot:",
    "passive": ":slowparrot:",
    "quiet": ":slowparrot:",
    "reluctant": ":slowparrot:",
    "sluggish": ":slowparrot:",
    "stagnant": ":slowparrot:",
    "crawling": ":slowparrot:",
    "creeping": ":slowparrot:",
    "dawdling": ":slowparrot:",
    "delaying": ":slowparrot:",
    "deliberate": ":slowparrot:",
    "disinclined": ":slowparrot:",
    "idle": ":slowparrot:",
    "lagging": ":slowparrot:",
    "loitering": ":slowparrot:",
    "measured": ":slowparrot:",
    "plodding": ":slowparrot:",
    "postponing": ":slowparrot:",
    "procrastinating": ":slowparrot:",
    "slack": ":slowparrot:",
    "apathetic": ":slowparrot:",
    "dilatory": ":slowparrot:",
    "dreamy": ":slowparrot:",
    "drowsy": ":slowparrot:",
    "inactive": ":slowparrot:",
    "indolent": ":slowparrot:",
    "inert": ":slowparrot:",
    "laggard": ":slowparrot:",
    "leaden": ":slowparrot:",
    "listless": ":slowparrot:",
    "negligent": ":slowparrot:",
    "phlegmatic": ":slowparrot:",
    "ponderous": ":slowparrot:",
    "remiss": ":slowparrot:",
    "slothful": ":slowparrot:",
    "slow-moving": ":slowparrot:",
    "snaillike": ":slowparrot:",
    "supine": ":slowparrot:",
    "tardy": ":slowparrot:",
    "torpid": ":slowparrot:",
    "tortoiselike": ":slowparrot:",


    "crypto": ":cryptoparrot:",
    "identification": ":cryptoparrot:",
    "countersign": ":cryptoparrot:",
    "key": ":cryptoparrot:",
    "parole": ":cryptoparrot:",
    "phrase": ":cryptoparrot:",
    "signal": ":cryptoparrot:",
    "ticket": ":cryptoparrot:",
    "watchword": ":cryptoparrot:",
    "word": ":cryptoparrot:",
    "key word": ":cryptoparrot:",
    "open sesame": ":cryptoparrot:",


    "fiesta": ":fiestaparrot:",
    "feast": ":fiestaparrot:",
    "carnival": ":fiestaparrot:",
    "festival": ":fiestaparrot:",
    "holiday": ":fiestaparrot:",
    "vacation": ":fiestaparrot:",
    "holy day": ":fiestaparrot:",
    "saint's day": ":fiestaparrot:",


    "fast": ":fastparrot:",
    "agile": ":fastparrot:",
    "brisk": ":fastparrot:",
    "nimble": ":fastparrot:",
    "quick": ":fastparrot:",
    "rapid": ":fastparrot:",
    "swift": ":fastparrot:",
    "accelerated": ":fastparrot:",
    "active": ":fastparrot:",
    "dashing": ":fastparrot:",
    "electric": ":fastparrot:",
    "flashing": ":fastparrot:",
    "fleet": ":fastparrot:",
    "fleeting": ":fastparrot:",
    "flying": ":fastparrot:",
    "hurried": ":fastparrot:",
    "racing": ":fastparrot:",
    "ready": ":fastparrot:",
    "snap": ":fastparrot:",
    "winged": ":fastparrot:",
    "PDQ": ":fastparrot:",
    "blue streak": ":fastparrot:",
    "breakneck": ":fastparrot:",
    "chop-chop": ":fastparrot:",
    "double-time": ":fastparrot:",
    "expeditious": ":fastparrot:",
    "expeditive": ":fastparrot:",
    "hairtrigger": ":fastparrot:",
    "hasty": ":fastparrot:",
    "hypersonic": ":fastparrot:",
    "in a jiffy": ":fastparrot:",
    "in nothing flat": ":fastparrot:",
    "lickety split": ":fastparrot:",
    "like a bat out of hell": ":fastparrot:",
    "like all get out": ":fastparrot:",
    "like crazy": ":fastparrot:",
    "like mad": ":fastparrot:",
    "on the double": ":fastparrot:",
    "posthaste": ":fastparrot:",
    "presto": ":fastparrot:",
    "pronto": ":fastparrot:",
    "screamin'": ":fastparrot:",
    "snappy": ":fastparrot:",
    "speedball": ":fastparrot:",
    "supersonic": ":fastparrot:",
    "velocious": ":fastparrot:",


    "science": ":scienceparrot:",
    "art": ":scienceparrot:",
    "discipline": ":scienceparrot:",
    "education": ":scienceparrot:",
    "information": ":scienceparrot:",
    "learning": ":scienceparrot:",
    "skill": ":scienceparrot:",
    "system": ":scienceparrot:",
    "technique": ":scienceparrot:",
    "branch": ":scienceparrot:",
    "erudition": ":scienceparrot:",
    "lore": ":scienceparrot:",
    "scholarship": ":scienceparrot:",
    "wisdom": ":scienceparrot:",
    "body of knowledge": ":scienceparrot:",


    "thumbs-up": ":thumbsupparrot:",
    "approval": ":thumbsupparrot:",
    "go-ahead": ":thumbsupparrot:",
    "green light": ":thumbsupparrot:",
    "rubber stamp": ":thumbsupparrot:",
    "satisfaction": ":thumbsupparrot:",


    "stable": ":stableparrot:",
    "balanced": ":stableparrot:",
    "calm": ":stableparrot:",
    "durable": ":stableparrot:",
    "lasting": ":stableparrot:",
    "permanent": ":stableparrot:",
    "reliable": ":stableparrot:",
    "safe": ":stableparrot:",
    "solid": ":stableparrot:",
    "steady": ":stableparrot:",
    "strong": ":stableparrot:",
    "substantial": ":stableparrot:",
    "abiding": ":stableparrot:",
    "anchored": ":stableparrot:",
    "enduring": ":stableparrot:",
    "established": ":stableparrot:",
    "even": ":stableparrot:",
    "firm": ":stableparrot:",
    "invariable": ":stableparrot:",
    "nailed": ":stableparrot:",
    "poised": ":stableparrot:",
    "set": ":stableparrot:",
    "sound": ":stableparrot:",
    "stabile": ":stableparrot:",
    "stalwart": ":stableparrot:",
    "staunch": ":stableparrot:",
    "stout": ":stableparrot:",
    "tough": ":stableparrot:",
    "uniform": ":stableparrot:",
    "brick-wall": ":stableparrot:",
    "deep-rooted": ":stableparrot:",
    "equable": ":stableparrot:",
    "immutable": ":stableparrot:",
    "perdurable": ":stableparrot:",
    "resolute": ":stableparrot:",
    "set in stone": ":stableparrot:",
    "solid as a rock": ":stableparrot:",
    "stationary": ":stableparrot:",
    "staying put": ":stableparrot:",
    "steadfast": ":stableparrot:",
    "sturdy": ":stableparrot:",
    "sure": ":stableparrot:",
    "together": ":stableparrot:",
    "unalterable": ":stableparrot:",
    "unchangeable": ":stableparrot:",
    "unfluctuating": ":stableparrot:",
    "unvarying": ":stableparrot:",
    "unwavering": ":stableparrot:",
    "well-built": ":stableparrot:",
    "well-founded": ":stableparrot:",


    "fieri": ":fieriparrot:",

    "explode": ":explodyparrot:",
    "boom": ":explodyparrot:",
    "blast": ":explodyparrot:",
    "break out": ":explodyparrot:",
    "burst": ":explodyparrot:",
    "collapse": ":explodyparrot:",
    "detonate": ":explodyparrot:",
    "erupt": ":explodyparrot:",
    "flare up": ":explodyparrot:",
    "mushroom": ":explodyparrot:",
    "rupture": ":explodyparrot:",
    "set off": ":explodyparrot:",
    "shatter": ":explodyparrot:",
    "backfire": ":explodyparrot:",
    "blaze": ":explodyparrot:",
    "convulse": ":explodyparrot:",
    "discharge": ":explodyparrot:",
    "fracture": ":explodyparrot:",
    "jet": ":explodyparrot:",
    "shiver": ":explodyparrot:",
    "split": ":explodyparrot:",
    "thunder": ":explodyparrot:",
    "blow to kingdom come": ":explodyparrot:",
    "flame up": ":explodyparrot:",
    "kablooey": ":explodyparrot:",
    "let go": ":explodyparrot:",


    "ultrafast": ":ultrafastparrot:",

    "doge": ":dogeparrot:",

    "margarita": ":margaritaparrot:",

    "beret": ":beretparrot:",
    "DINK": ":beretparrot:",
    "beanie": ":beretparrot:",
    "bonnet": ":beretparrot:",
    "fez": ":beretparrot:",
    "pillbox": ":beretparrot:",
    "skullcap": ":beretparrot:",
    "tam": ":beretparrot:",


    "angry": ":angryparrot:",
    "mad": ":angryparrot:",
    "annoyed": ":angryparrot:",
    "enraged": ":angryparrot:",
    "exasperated": ":angryparrot:",
    "furious": ":angryparrot:",
    "heated": ":angryparrot:",
    "impassioned": ":angryparrot:",
    "indignant": ":angryparrot:",
    "irate": ":angryparrot:",
    "irritable": ":angryparrot:",
    "irritated": ":angryparrot:",
    "offended": ":angryparrot:",
    "outraged": ":angryparrot:",
    "resentful": ":angryparrot:",
    "sullen": ":angryparrot:",
    "uptight": ":angryparrot:",
    "affronted": ":angryparrot:",
    "antagonized": ":angryparrot:",
    "chafed": ":angryparrot:",
    "choleric": ":angryparrot:",
    "convulsed": ":angryparrot:",
    "cross": ":angryparrot:",
    "displeased": ":angryparrot:",
    "exacerbated": ":angryparrot:",
    "ferocious": ":angryparrot:",
    "fierce": ":angryparrot:",
    "fiery": ":angryparrot:",
    "fuming": ":angryparrot:",
    "galled": ":angryparrot:",
    "hot": ":angryparrot:",
    "huffy": ":angryparrot:",
    "ill-tempered": ":angryparrot:",
    "incensed": ":angryparrot:",
    "inflamed": ":angryparrot:",
    "infuriated": ":angryparrot:",
    "irascible": ":angryparrot:",
    "ireful": ":angryparrot:",
    "maddened": ":angryparrot:",
    "nettled": ":angryparrot:",
    "piqued": ":angryparrot:",
    "provoked": ":angryparrot:",
    "raging": ":angryparrot:",
    "riled": ":angryparrot:",
    "sore": ":angryparrot:",
    "splenetic": ":angryparrot:",
    "storming": ":angryparrot:",
    "sulky": ":angryparrot:",
    "tumultous": ":angryparrot:",
    "turbulent": ":angryparrot:",
    "vexed": ":angryparrot:",


    "hamburger": ":hamburgerparrot:",
    "beefburger": ":hamburgerparrot:",
    "burger": ":hamburgerparrot:",
    "cheeseburger": ":hamburgerparrot:",
    "Salisbury steak": ":hamburgerparrot:",
    "chopped beefsteak": ":hamburgerparrot:",
    "ground chuck": ":hamburgerparrot:",
    "ground round": ":hamburgerparrot:",
    "ground sirloin": ":hamburgerparrot:",


    "shuffle": ":shuffleparrot:",
    "drag": "shuffleparrot:",
    "limp": "shuffleparrot:",
    "straggle": "shuffleparrot:",
    "stumble": "shuffleparrot:",
    "muddle": "shuffleparrot:",
    "pad": "shuffleparrot:",
    "scrape": "shuffleparrot:",
    "scuff": "shuffleparrot:",
    "scuffle": "shuffleparrot:",
    "shamble": "shuffleparrot:",
    "trail": "shuffleparrot:",


    "ice-cream": ":ice-cream-parrot:",
    "frozen yogurt": "ice-cream-parrot:",
    "sherbet": "ice-cream-parrot:",
    "sorbet": "ice-cream-parrot:",
    "gelato": "ice-cream-parrot:",
    "ice": "ice-cream-parrot:",
    "ice milk": "ice-cream-parrot:",


    "brazilian fan": ":brazilianfanparrot:",

    "coffee": ":coffeeparrot:",
    "caffeine": "coffeeparrot:",
    "cappuccino": "coffeeparrot:",
    "espresso": "coffeeparrot:",
    "brew": "coffeeparrot:",
    "decaf": "coffeeparrot:",
    "decoction": "coffeeparrot:",
    "demitasse": "coffeeparrot:",
    "ink": "coffeeparrot:",
    "java": "coffeeparrot:",
    "mocha": "coffeeparrot:",
    "mud": "coffeeparrot:",
    "perk": "coffeeparrot:",
    "battery acid": "coffeeparrot:",
    "café": "coffeeparrot:",
    "café au lait": "coffeeparrot:",
    "café noir": "coffeeparrot:",
    "forty weight": "coffeeparrot:",
    "hot stuff": "coffeeparrot:",
    "jamocha": "coffeeparrot:",


    "conga doge": ":congadoge:",

    "christmas": ":christmasparrot:",
    "Christmastide": "christmasparrot:",
    "Noel": "christmasparrot:",
    "Xmas": "christmasparrot:",
    "Yule": "christmasparrot:",
    "Yuletide": "christmasparrot:",
    "Christmas Day": "christmasparrot:",
    "Christmas Eve": "christmasparrot:",
    "Christmas night": "christmasparrot:",
    "the Nativity": "christmasparrot:",


    "pride": ":prideparrot:",
    "dignity": "prideparrot:",
    "ego": "prideparrot:",
    "happiness": "prideparrot:",
    "honor": "prideparrot:",
    "joy": "prideparrot:",
    "pleasure": "prideparrot:",
    "self-confidence": "prideparrot:",
    "self-respect": "prideparrot:",
    "egoism": "prideparrot:",
    "egotism": "prideparrot:",
    "face": "prideparrot:",
    "gratification": "prideparrot:",
    "pridefulness": "prideparrot:",
    "repletion": "prideparrot:",
    "self-love": "prideparrot:",
    "self-regard": "prideparrot:",
    "self-satisfaction": "prideparrot:",
    "self-sufficiency": "prideparrot:",
    "self-worth": "prideparrot:",
    "sufficiency": "prideparrot:",
    "amour-propre": "prideparrot:",
    "ego trip": "prideparrot:",
    "self-admiration": "prideparrot:",
    "self-glorification": "prideparrot:",
    "self-trust": "prideparrot:",



    "blonde": ":blondesassyparrot:",
    "blond": "blondesassyparrot:",
    "albino": "blondesassyparrot:",
    "champagne": "blondesassyparrot:",
    "fair": "blondesassyparrot:",
    "light": "blondesassyparrot:",
    "pale": "blondesassyparrot:",
    "platinum": "blondesassyparrot:",
    "sallow": "blondesassyparrot:",
    "straw": "blondesassyparrot:",
    "strawberry": "blondesassyparrot:",
    "auricomous": "blondesassyparrot:",
    "bleached": "blondesassyparrot:",
    "fair-haired": "blondesassyparrot:",
    "flaxen": "blondesassyparrot:",
    "golden-haired": "blondesassyparrot:",
    "leucous": "blondesassyparrot:",
    "sandy-haired": "blondesassyparrot:",
    "snowy": "blondesassyparrot:",
    "stramineous": "blondesassyparrot:",
    "towheaded": "blondesassyparrot:",
    "washed-out": "blondesassyparrot:",
    "yellow-haired": "blondesassyparrot:",


    "fix": ":fixparrot:",
    "mend": ":fixparrot:",
    "install": "fixparrot:",
    "secure": "fixparrot:",
    "settle": "fixparrot:",
    "stabilize": "fixparrot:",
    "affix": "fixparrot:",
    "anchor": "fixparrot:",
    "attach": "fixparrot:",
    "bind": "fixparrot:",
    "catch": "fixparrot:",
    "cement": "fixparrot:",
    "congeal": "fixparrot:",
    "connect": "fixparrot:",
    "consolidate": "fixparrot:",
    "couple": "fixparrot:",
    "embed": "fixparrot:",
    "entrench": "fixparrot:",
    "fasten": "fixparrot:",
    "glue": "fixparrot:",
    "graft": "fixparrot:",
    "harden": "fixparrot:",
    "implant": "fixparrot:",
    "inculcate": "fixparrot:",
    "infix": "fixparrot:",
    "ingrain": "fixparrot:",
    "instill": "fixparrot:",
    "link": "fixparrot:",
    "locate": "fixparrot:",
    "lodge": "fixparrot:",
    "moor": "fixparrot:",
    "pin": "fixparrot:",
    "place": "fixparrot:",
    "plant": "fixparrot:",
    "position": "fixparrot:",
    "rigidify": "fixparrot:",
    "rivet": "fixparrot:",
    "root": "fixparrot:",
    "solidify": "fixparrot:",
    "stick": "fixparrot:",
    "stiffen": "fixparrot:",
    "thicken": "fixparrot:",
    "tie": "fixparrot:",
    "freeze to": "fixparrot:",
    "nail down": "fixparrot:",
    "stay put": "fixparrot:",
    "adjust": "fixparrot:",
    "overhaul": "fixparrot:",
    "patch": "fixparrot:",
    "rebuild": "fixparrot:",
    "regulate": "fixparrot:",
    "restore": "fixparrot:",
    "revamp": "fixparrot:",
    "revise": "fixparrot:",
    "amend": "fixparrot:",
    "debug": "fixparrot:",
    "doctor": "fixparrot:",
    "emend": "fixparrot:",
    "face-lift": "fixparrot:",
    "recondition": "fixparrot:",
    "reconstruct": "fixparrot:",
    "retread": "fixparrot:",
    "sort": "fixparrot:",
    "do up": "fixparrot:",
    "fiddle with": "fixparrot:",
    "put to rights": "fixparrot:",
    "see to": "fixparrot:",
    "tune up": "fixparrot:",


    "triplets": ":tripletsparrot:",
    "leash": "tripletsparrot:",
    "set of three": "tripletsparrot:",
    "ternion": "tripletsparrot:",
    "threesome": "tripletsparrot:",
    "trey": "tripletsparrot:",
    "triad": "tripletsparrot:",
    "triangle": "tripletsparrot:",
    "trilogy": "tripletsparrot:",
    "trine": "tripletsparrot:",
    "trinity": "tripletsparrot:",
    "triplet": "tripletsparrot:",
    "triplicate": "tripletsparrot:",
    "triptych": "tripletsparrot:",
    "triumvirate": "tripletsparrot:",
    "triune": "tripletsparrot:",
    "troika": "tripletsparrot:",


    "harry potter": ":harrypotterparrot:",
    "Harry Potter": "harrypotterparrot:",
    "Ron Weasley": "harrypotterparrot:",
    "Hermione Granger": "harrypotterparrot:",
    "Albus Dumbledore": "harrypotterparrot:",
    "Argus Filch": "harrypotterparrot:",
    "Armando Dippet": "harrypotterparrot:",
    "Aurora Sinistra": "harrypotterparrot:",
    "Charity Burbage": "harrypotterparrot:",
    "Filius Flitwick": "harrypotterparrot:",
    "Gilderoy Lockhart": "harrypotterparrot:",
    "Horace Slughorn": "harrypotterparrot:",
    "Irma Pince": "harrypotterparrot:",
    "Minerva McGonagall": "harrypotterparrot:",
    "Nurse Wainscott": "harrypotterparrot:",
    "Pomona Sprout": "harrypotterparrot:",
    "Poppy Pomfrey": "harrypotterparrot:",
    "Quirinus Quirrell": "harrypotterparrot:",
    "Rolanda Hooch": "harrypotterparrot:",
    "Rubeus Hagrid": "harrypotterparrot:",
    "Septima Vector": "harrypotterparrot:",
    "Severus Snape": "harrypotterparrot:",
    "Sybill Trelawney": "harrypotterparrot:",
    "Wilhelmina Grubbly-Plank": "harrypotterparrot:",
    "Unidentified Professors": "harrypotterparrot:",
    "The Bloody Baron": "harrypotterparrot:",
    "Sir Cadogan": "harrypotterparrot:",
    "Everard": "harrypotterparrot:",
    "Fang": "harrypotterparrot:",
    "The Fat Friar": "harrypotterparrot:",
    "Fat Lady": "harrypotterparrot:",
    "The Grey Lady": "harrypotterparrot:",
    "Myrtle Warren": "harrypotterparrot:",
    "Nearly Headless Nick": "harrypotterparrot:",
    "Phineas Nigellus Black": "harrypotterparrot:",
    "Peeves": "harrypotterparrot:",
    "Sorting Hat": "harrypotterparrot:",
    "Unidentified Ghosts": "harrypotterparrot:",
    "Adrian Pucey": "harrypotterparrot:",
    "Alicia Spinnet": "harrypotterparrot:",
    "Alys": "harrypotterparrot:",
    "Amanda": "harrypotterparrot:",
    "Angelina Johnson": "harrypotterparrot:",
    "Anthony Goldstein": "harrypotterparrot:",
    "Bem": "harrypotterparrot:",
    "Blaise Zabini": "harrypotterparrot:",
    "Cedric Diggory": "harrypotterparrot:",
    "Cho Chang": "harrypotterparrot:",
    "Colin Creevey": "harrypotterparrot:",
    "Cormac McLaggen": "harrypotterparrot:",
    "Dean Thomas": "harrypotterparrot:",
    "Draco Malfoy": "harrypotterparrot:",
    "Demelza Robins": "harrypotterparrot:",
    "Eloise Midgen": "harrypotterparrot:",
    "Ernie Macmillan": "harrypotterparrot:",
    "Fay Dunbar": "harrypotterparrot:",
    "Flora Carrow": "harrypotterparrot:",
    "Fred Weasley": "harrypotterparrot:",
    "George Weasley": "harrypotterparrot:",
    "Ginny Weasley": "harrypotterparrot:",
    "Gregory Goyle": "harrypotterparrot:",
    "Hannah Abbott": "harrypotterparrot:",
    "Hestia Carrow": "harrypotterparrot:",
    "Jimmy Peakes": "harrypotterparrot:",
    "Justin Finch-Fletchley": "harrypotterparrot:",
    "Katie Bell": "harrypotterparrot:",
    "Kellah": "harrypotterparrot:",
    "Lavender Brown": "harrypotterparrot:",
    "Leanne": "harrypotterparrot:",
    "Lee Jordan": "harrypotterparrot:",
    "Luna Lovegood": "harrypotterparrot:",
    "Marcus Belby": "harrypotterparrot:",


    "lucky": ":luckyparrot:",
    "fortuitous": "luckyparrot:",
    "happy": "luckyparrot:",
    "successful": "luckyparrot:",
    "advantageous": "luckyparrot:",
    "adventitious": "luckyparrot:",
    "all systems go": "luckyparrot:",
    "auspicious": "luckyparrot:",
    "beneficial": "luckyparrot:",
    "benign": "luckyparrot:",
    "blessed": "luckyparrot:",
    "charmed": "luckyparrot:",
    "coming up roses": "luckyparrot:",
    "everything going": "luckyparrot:",
    "favored": "luckyparrot:",
    "felicitous": "luckyparrot:",
    "getting a break": "luckyparrot:",
    "golden": "luckyparrot:",
    "hit it big": "luckyparrot:",
    "holding aces": "luckyparrot:",
    "hopeful": "luckyparrot:",
    "in the groove": "luckyparrot:",
    "into something": "luckyparrot:",
    "on a roll": "luckyparrot:",
    "on a streak": "luckyparrot:",
    "promising": "luckyparrot:",
    "propitious": "luckyparrot:",
    "prosperous": "luckyparrot:",
    "providential": "luckyparrot:",
    "serendipitous": "luckyparrot:",
    "striking it rich": "luckyparrot:",
    "timely": "luckyparrot:",
    "well": "luckyparrot:",


    "right": ":rightparrot:",
    "appropriate": "rightparrot:",
    "good": "rightparrot:",
    "honest": "rightparrot:",
    "honorable": "rightparrot:",
    "legal": "rightparrot:",
    "legitimate": "rightparrot:",
    "suitable": "rightparrot:",
    "TRUE": "rightparrot:",
    "deserved": "rightparrot:",
    "due": "rightparrot:",
    "fitting": "rightparrot:",
    "merited": "rightparrot:",
    "moral": "rightparrot:",
    "requisite": "rightparrot:",
    "upright": "rightparrot:",
    "condign": "rightparrot:",
    "conscientious": "rightparrot:",
    "equitable": "rightparrot:",
    "ethical": "rightparrot:",
    "justifiable": "rightparrot:",
    "lawful": "rightparrot:",
    "righteous": "rightparrot:",
    "rightful": "rightparrot:",
    "scrupulous": "rightparrot:",
    "stand-up": "rightparrot:",
    "virtuous": "rightparrot:",
    "correct": "rightparrot:",
    "perfect": "rightparrot:",
    "proper": "rightparrot:",
    "true": "rightparrot:",
    "valid": "rightparrot:",
    "absolute": "rightparrot:",
    "amen": "rightparrot:",
    "complete": "rightparrot:",
    "exact": "rightparrot:",
    "faithful": "rightparrot:",
    "nice": "rightparrot:",
    "real": "rightparrot:",
    "utter": "rightparrot:",
    "admissible": "rightparrot:",
    "authentic": "rightparrot:",
    "bona fide": "rightparrot:",
    "factual": "rightparrot:",
    "free of error": "rightparrot:",
    "genuine": "rightparrot:",
    "immaculate": "rightparrot:",
    "indubitable": "rightparrot:",
    "inerrant": "rightparrot:",
    "infallible": "rightparrot:",
    "just": "rightparrot:",
    "on the money": "rightparrot:",
    "on the nose": "rightparrot:",
    "out-and-out": "rightparrot:",
    "punctilious": "rightparrot:",
    "right as rain": "rightparrot:",
    "right on": "rightparrot:",
    "rigorous": "rightparrot:",
    "satisfactory": "rightparrot:",
    "solemn": "rightparrot:",
    "strict": "rightparrot:",
    "thoroughgoing": "rightparrot:",
    "undistorted": "rightparrot:",
    "undoubted": "rightparrot:",
    "unerring": "rightparrot:",
    "unmistaken": "rightparrot:",
    "veracious": "rightparrot:",
    "veridical": "rightparrot:",
    "veritable": "rightparrot:",
    "watertight": "rightparrot:",


    "ship it": ":shipitparrot:",
    "release": ":shipitparrot:",
    "dispatch": "shipitparrot:",
    "export": "shipitparrot:",
    "haul": "shipitparrot:",
    "move": "shipitparrot:",
    "shift": "shipitparrot:",
    "smuggle": "shipitparrot:",
    "transfer": "shipitparrot:",
    "transmit": "shipitparrot:",
    "address": "shipitparrot:",
    "consign": "shipitparrot:",
    "direct": "shipitparrot:",
    "drop": "shipitparrot:",
    "embark": "shipitparrot:",
    "forward": "shipitparrot:",
    "freight": "shipitparrot:",
    "remit": "shipitparrot:",
    "route": "shipitparrot:",
    "go aboard": "shipitparrot:",
    "put on board": "shipitparrot:",
    "ship out": "shipitparrot:",

    "angel": ":angelparrot:",
    "beauty": "angelparrot:",
    "darling": "angelparrot:",
    "dear": "angelparrot:",
    "gem": "angelparrot:",
    "ideal": "angelparrot:",
    "jewel": "angelparrot:",
    "paragon": "angelparrot:",
    "saint": "angelparrot:",
    "treasure": "angelparrot:",
    "archangel": "angelparrot:",
    "cherub": "angelparrot:",
    "guardian": "angelparrot:",
    "seraph": "angelparrot:",
    "spirit": "angelparrot:",
    "sprite": "angelparrot:",
    "God's messenger": "angelparrot:",
    "celestial being": "angelparrot:",
    "divine messenger": "angelparrot:",
    "heavenly being": "angelparrot:",
    "holy being": "angelparrot:",
    "spiritual being": "angelparrot:",


    "shuffle further": ":shufflefurtherparrot:",

    "caps": ":capsparrot:",

    "aussie": ":aussieparrot:",

    "deal with it": ":dealwithitparrot:",

    "stalker": ":stalkerparrot:",
    "chaser": "stalkerparrot:",
    "deerstalker": "stalkerparrot:",
    "falconer": "stalkerparrot:",
    "fisherman": "stalkerparrot:",
    "hawker": "stalkerparrot:",
    "huntress": "stalkerparrot:",
    "huntsman": "stalkerparrot:",
    "pursuer": "stalkerparrot:",
    "sportsman": "stalkerparrot:",
    "trapper": "stalkerparrot:",
    "ferreter": "stalkerparrot:",
    "pursuant": "stalkerparrot:",

    "ski": ":skiparrot:",

    "nyan": ":nyanparrot:",

    "gentleman": ":gentlemanparrot:",
    "cavalier": "gentlemanparrot:",
    "don": "gentlemanparrot:",
    "sir": "gentlemanparrot:",
    "man of his word": "gentlemanparrot:",
    "man of honor": "gentlemanparrot:",
    "polished man": "gentlemanparrot:",
    "refined man": "gentlemanparrot:",
    "aristocrat": "gentlemanparrot:",
    "nobleman": "gentlemanparrot:",
    "lord": "gentlemanparrot:",
    "patrician": "gentlemanparrot:",
    "man of breeding": "gentlemanparrot:",


    "papal": ":papalparrot:",
    "apostolic": "papalparrot:",
    "pontifical": "papalparrot:",
    "papistic": "papalparrot:",


    "cops": ":parrotcop:",
    "police": ":parrotcop:",
    "detective": "parrotcop:",
    "force": "parrotcop:",
    "law enforcement": "parrotcop:",
    "man": "parrotcop:",
    "badge": "parrotcop:",
    "bear": "parrotcop:",
    "blue": "parrotcop:",
    "bluecoat": "parrotcop:",
    "bobby": "parrotcop:",
    "bull": "parrotcop:",
    "constable": "parrotcop:",
    "constabulary": "parrotcop:",
    "cop": "parrotcop:",
    "copper": "parrotcop:",
    "corps": "parrotcop:",
    "fed": "parrotcop:",
    "flatfoot": "parrotcop:",
    "fuzz": "parrotcop:",
    "gendarme": "parrotcop:",
    "gumshoe": "parrotcop:",
    "heat": "parrotcop:",
    "law": "parrotcop:",
    "narc": "parrotcop:",
    "officers": "parrotcop:",
    "oink": "parrotcop:",
    "patrolman": "parrotcop:",
    "pig": "parrotcop:",
    "boy scout": "parrotcop:",
    "county mounty": "parrotcop:",


    "witness protection": ":witnessprotectionparrot:",
    "secret": ":witnessprotectionparrot:",
    "hide": ":witnessprotectionparrot:",
    "classified": "witnessprotectionparrot:",
    "covert": "witnessprotectionparrot:",
    "furtive": "witnessprotectionparrot:",
    "hush-hush": "witnessprotectionparrot:",
    "mysterious": "witnessprotectionparrot:",
    "obscure": "witnessprotectionparrot:",
    "private": "witnessprotectionparrot:",
    "secluded": "witnessprotectionparrot:",
    "undercover": "witnessprotectionparrot:",
    "underground": "witnessprotectionparrot:",
    "undisclosed": "witnessprotectionparrot:",
    "unknown": "witnessprotectionparrot:",
    "unpublished": "witnessprotectionparrot:",
    "backdoor": "witnessprotectionparrot:",
    "close": "witnessprotectionparrot:",
    "closet": "witnessprotectionparrot:",
    "dark": "witnessprotectionparrot:",
    "deep": "witnessprotectionparrot:",
    "mystic": "witnessprotectionparrot:",
    "occult": "witnessprotectionparrot:",
    "unseen": "witnessprotectionparrot:",
    "abstruse": "witnessprotectionparrot:",
    "ambiguous": "witnessprotectionparrot:",
    "arcane": "witnessprotectionparrot:",
    "camouflaged": "witnessprotectionparrot:",
    "cloak-and-dagger": "witnessprotectionparrot:",
    "clouded": "witnessprotectionparrot:",
    "conspiratorial": "witnessprotectionparrot:",
    "covered": "witnessprotectionparrot:",
    "cryptic": "witnessprotectionparrot:",
    "disguised": "witnessprotectionparrot:",
    "enigmatical": "witnessprotectionparrot:",
    "esoteric": "witnessprotectionparrot:",
    "mystical": "witnessprotectionparrot:",
    "on the QT": "witnessprotectionparrot:",
    "out-of-the-way": "witnessprotectionparrot:",
    "recondite": "witnessprotectionparrot:",
    "reticent": "witnessprotectionparrot:",
    "retired": "witnessprotectionparrot:",
    "shrouded": "witnessprotectionparrot:",
    "strange": "witnessprotectionparrot:",
    "under wraps": "witnessprotectionparrot:",
    "unenlightened": "witnessprotectionparrot:",
    "unfrequented": "witnessprotectionparrot:",
    "unintelligible": "witnessprotectionparrot:",
    "veiled": "witnessprotectionparrot:",


    "dreidel": ":dreidelparrot:",

    "aussie reverse conga": ":aussiereversecongaparrot:",

    "dad": ":parrotdad:",
    "papa": ":parrotdad:",
    "father": ":parrotdad:",

    "sad": ":sadparrot:",
    "upset": ":sadparrot:",
    "cry": ":sadparrot:",
    "bitter": "sadparrot:",
    "dismal": "sadparrot:",
    "heartbroken": "sadparrot:",
    "melancholy": "sadparrot:",
    "mournful": "sadparrot:",
    "pessimistic": "sadparrot:",
    "somber": "sadparrot:",
    "sorrowful": "sadparrot:",
    "sorry": "sadparrot:",
    "wistful": "sadparrot:",
    "bereaved": "sadparrot:",
    "cheerless": "sadparrot:",
    "dejected": "sadparrot:",
    "despairing": "sadparrot:",
    "despondent": "sadparrot:",
    "disconsolate": "sadparrot:",
    "distressed": "sadparrot:",
    "doleful": "sadparrot:",
    "down": "sadparrot:",
    "down in dumps": "sadparrot:",
    "down in mouth": "sadparrot:",
    "downcast": "sadparrot:",
    "forlorn": "sadparrot:",
    "gloomy": "sadparrot:",
    "glum": "sadparrot:",
    "grief-stricken": "sadparrot:",
    "grieved": "sadparrot:",
    "heartsick": "sadparrot:",
    "heavyhearted": "sadparrot:",
    "hurting": "sadparrot:",
    "in doldrums": "sadparrot:",
    "in grief": "sadparrot:",
    "in the dumps": "sadparrot:",
    "languishing": "sadparrot:",
    "low-spirited": "sadparrot:",
    "lugubrious": "sadparrot:",
    "morbid": "sadparrot:",
    "morose": "sadparrot:",
    "out of sorts": "sadparrot:",
    "pensive": "sadparrot:",
    "sick at heart": "sadparrot:",
    "troubled": "sadparrot:",
    "weeping": "sadparrot:",
    "woebegone": "sadparrot:",


    "old timer": ":oldtimeyparrot:",
    "old": ":oldtimeyparrot:",
    "aged": "oldtimeyparrot:",
    "ancient": "oldtimeyparrot:",
    "decrepit": "oldtimeyparrot:",
    "elderly": "oldtimeyparrot:",
    "gray": "oldtimeyparrot:",
    "mature": "oldtimeyparrot:",
    "venerable": "oldtimeyparrot:",
    "fossil": "oldtimeyparrot:",
    "senior": "oldtimeyparrot:",
    "versed": "oldtimeyparrot:",
    "veteran": "oldtimeyparrot:",
    "along in years": "oldtimeyparrot:",
    "broken down": "oldtimeyparrot:",
    "debilitated": "oldtimeyparrot:",
    "enfeebled": "oldtimeyparrot:",
    "exhausted": "oldtimeyparrot:",
    "experienced": "oldtimeyparrot:",
    "geriatric": "oldtimeyparrot:",
    "getting on": "oldtimeyparrot:",
    "gray-haired": "oldtimeyparrot:",
    "grizzled": "oldtimeyparrot:",
    "hoary": "oldtimeyparrot:",
    "impaired": "oldtimeyparrot:",
    "infirm": "oldtimeyparrot:",
    "matured": "oldtimeyparrot:",
    "not young": "oldtimeyparrot:",
    "olden": "oldtimeyparrot:",
    "oldish": "oldtimeyparrot:",
    "over the hill": "oldtimeyparrot:",
    "past one's prime": "oldtimeyparrot:",
    "seasoned": "oldtimeyparrot:",
    "senile": "oldtimeyparrot:",
    "skilled": "oldtimeyparrot:",
    "superannuated": "oldtimeyparrot:",
    "wasted": "oldtimeyparrot:",


    "wave": ":parrotwave1::parrotwave2::parrotwave3::parrotwave4::parrotwave5::parrotwave6::parrotwave7:",
    "mexican wave": ":parrotwave1::parrotwave2::parrotwave3::parrotwave4::parrotwave5::parrotwave6::parrotwave7:",

    "pizza": ":pizzaparrot:",

    "mustache": ":parrotmustache:",

    "aussie conga": ":aussiecongaparrot:",

    "moonwalking": ":moonwalkingparrot:",

    "fidget": ":fidgetparrot:",
    "fret": "fidgetparrot:",
    "jiggle": "fidgetparrot:",
    "squirm": "fidgetparrot:",
    "twiddle": "fidgetparrot:",
    "twitch": "fidgetparrot:",
    "bustle": "fidgetparrot:",
    "chafe": "fidgetparrot:",
    "fiddle": "fidgetparrot:",
    "fuss": "fidgetparrot:",
    "hitch": "fidgetparrot:",
    "jitter": "fidgetparrot:",
    "joggle": "fidgetparrot:",
    "play": "fidgetparrot:",
    "stir": "fidgetparrot:",
    "toss": "fidgetparrot:",
    "trifle": "fidgetparrot:",
    "wiggle": "fidgetparrot:",
    "worry": "fidgetparrot:",
    "be antsy": "fidgetparrot:",
    "be hyper": "fidgetparrot:",
    "be nervous": "fidgetparrot:",
    "be on pins and needles": "fidgetparrot:",
    "be spooked": "fidgetparrot:",
    "be wired": "fidgetparrot:",


    "taco": ":tacoparrot:",

    "goth": ":gothparrot:",


    "bored": ":boredparrot:",
    "fed-up": ":boredparrot:",
    "disinterested": "boredparrot:",
    "fatigued": "boredparrot:",
    "dull": "boredparrot:",
    "blasé": "boredparrot:",
    "inattentive": "boredparrot:",
    "sick and tired": "boredparrot:",
    "spiritless": "boredparrot:",


    "blues clues": ":bluescluesparrot:",

    "upvote": ":upvotepartyparrot:",
    "affirmative": "upvotepartyparrot:",
    "fine": "upvotepartyparrot:",
    "okay": "upvotepartyparrot:",
    "yea": "upvotepartyparrot:",
    "all right": "upvotepartyparrot:",
    "aye": "upvotepartyparrot:",
    "beyond a doubt": "upvotepartyparrot:",
    "by all means": "upvotepartyparrot:",
    "certainly": "upvotepartyparrot:",
    "definitely": "upvotepartyparrot:",
    "even so": "upvotepartyparrot:",
    "exactly": "upvotepartyparrot:",
    "gladly": "upvotepartyparrot:",
    "good enough": "upvotepartyparrot:",
    "granted": "upvotepartyparrot:",
    "indubitably": "upvotepartyparrot:",
    "just so": "upvotepartyparrot:",
    "most assuredly": "upvotepartyparrot:",
    "naturally": "upvotepartyparrot:",
    "of course": "upvotepartyparrot:",
    "positively": "upvotepartyparrot:",
    "precisely": "upvotepartyparrot:",
    "sure thing": "upvotepartyparrot:",
    "surely": "upvotepartyparrot:",
    "undoubtedly": "upvotepartyparrot:",
    "unquestionably": "upvotepartyparrot:",
    "very well": "upvotepartyparrot:",
    "willingly": "upvotepartyparrot:",
    "without fail": "upvotepartyparrot:",
    "yep": "upvotepartyparrot:",


    "reverse conga": ":reversecongaparrot:",

    "twins": ":twinsparrot:",
    "double": ":twinsparrot:",

    "opensource": ":opensourceparrot:",
    "programming": ":opensourceparrot:",
    "coding": ":opensourceparrot:",

    "brazilianplayer": ":brazilianplayerparrot:",

    "ceiling": ":ceilingparrot:",
    "roof": ":ceilingparrot:",

    "conga party": ":congapartyparrot:",

    "middle": ":middleparrot:",

    "party": ":partyparrot:",
    "celebration": "partyparrot:",
    "dinner": "partyparrot:",
    "affair": "partyparrot:",
    "amusement": "partyparrot:",
    "ball": "partyparrot:",
    "banquet": "partyparrot:",
    "barbecue": "partyparrot:",
    "bash": "partyparrot:",
    "blowout": "partyparrot:",
    "carousal": "partyparrot:",
    "carousing": "partyparrot:",
    "cocktails": "partyparrot:",
    "diversion": "partyparrot:",
    "do": "partyparrot:",
    "entertainment": "partyparrot:",
    "festivity": "partyparrot:",
    "fete": "partyparrot:",
    "fun": "partyparrot:",
    "function": "partyparrot:",
    "gala": "partyparrot:",
    "luncheon": "partyparrot:",
    "orgy": "partyparrot:",
    "prom": "partyparrot:",
    "reception": "partyparrot:",
    "riot": "partyparrot:",
    "shindig": "partyparrot:",
    "social": "partyparrot:",
    "soiree": "partyparrot:",
    "splurge": "partyparrot:",
    "spree": "partyparrot:",
    "tea": "partyparrot:",
    "at-home": "partyparrot:",
    "coffee klatch": "partyparrot:",
    "coming-out": "partyparrot:",
    "festive occasion": "partyparrot:",
    "get-together": "partyparrot:",
    "movable feast": "partyparrot:",


    "sleep": ":parrotsleep:",
    "tired": ":parrotsleep:",
    "sleepy": ":parrotsleep:",
    "bed": ":parrotsleep:",
    "coma": "parrotsleep:",
    "dream": "parrotsleep:",
    "hibernation": "parrotsleep:",
    "slumber": "parrotsleep:",
    "trance": "parrotsleep:",
    "bedtime": "parrotsleep:",
    "catnap": "parrotsleep:",
    "dormancy": "parrotsleep:",
    "doze": "parrotsleep:",
    "dullness": "parrotsleep:",
    "lethargy": "parrotsleep:",
    "nap": "parrotsleep:",
    "nod": "parrotsleep:",
    "repose": "parrotsleep:",
    "rest": "parrotsleep:",
    "sandman": "parrotsleep:",
    "shuteye": "parrotsleep:",
    "siesta": "parrotsleep:",
    "snooze": "parrotsleep:",
    "torpidity": "parrotsleep:",
    "torpor": "parrotsleep:",
    "few z's": "parrotsleep:",
    "forty winks": "parrotsleep:",
    "sack time": "parrotsleep:",
    "slumberland": "parrotsleep:",
    "bed down": "parrotsleep:",
    "fall asleep": "parrotsleep:",
    "languish": "parrotsleep:",
    "relax": "parrotsleep:",
    "bunk": "parrotsleep:",
    "crash": "parrotsleep:",
    "drowse": "parrotsleep:",
    "flop": "parrotsleep:",
    "hibernate": "parrotsleep:",
    "oversleep": "parrotsleep:",
    "retire": "parrotsleep:",
    "snore": "parrotsleep:",
    "yawn": "parrotsleep:",
    "catch a wink": "parrotsleep:",
    "catch forty winks": "parrotsleep:",
    "conk out": "parrotsleep:",
    "cop some z's": "parrotsleep:",
    "drop off": "parrotsleep:",
    "fall out": "parrotsleep:",
    "hit the hay": "parrotsleep:",
    "hit the sack": "parrotsleep:",
    "nod off": "parrotsleep:",
    "sack out": "parrotsleep:",
    "saw wood": "parrotsleep:",
    "take a nap": "parrotsleep:",
    "turn in": "parrotsleep:",
    "zonk out": "parrotsleep:",
    "zzz": "parrotsleep:",


    "beer": ":parrotbeer:",
    "wine": ":parrotbeer:",
    "alchohol": ":parrotbeer:",
    "pub": ":parrotbeer:",

    "shuffle party": ":shufflepartyparrot:",

    "parrot": ":parrot:"
}
